### ISSUE TITLE
界面修改1

### ISSUE THREAD

**Issue by grimmnane** [grimmnane/aiotlp#1]
![image](https://user-images.githubusercontent.com/73623672/99344707-a2d0d800-28cb-11eb-8221-4755afed0c47.png)
名字和手机号居中

![image](https://user-images.githubusercontent.com/73623672/99344740-bb40f280-28cb-11eb-8ca4-b7ce7533b5e4.png)
缺省选中

![image](https://user-images.githubusercontent.com/73623672/99344812-e1ff2900-28cb-11eb-8a83-de17c95bf113.png)
窗口和按钮颜色协调，真不行，就一样颜色

**Comment by tracy-yang** [comment]
已修复
