### ISSUE TITLE
我的分享，出现null

### ISSUE THREAD

**Issue by grimmnane** [grimmnane/aiotlp#4]
![image](https://user-images.githubusercontent.com/73623672/99468413-7d9ba280-297b-11eb-8208-bd87da1c6cba.png)
名字 出现null

**Comment by tracy-yang** [comment]
设置由于没有用户昵称的原因。没有用户昵称的原因是：小程序必须要手动的授权一下才能拿到用户信息。目前产品没有定性如何处理授权的事情。目前的解决方案是：有用户名显示用户名，没有用户名显示：用户 139****4874
